### ISSUE TITLE
setSpeed

### ISSUE THREAD

**Issue by gcl8a** [WPIRoboticsEngineering/RBE1001Lib#21]
Speaking of integral control...the "Red Queen" solution that I described suffers from excessive integral windup under the right conditions. If the setPoint keeps moving in front of the current position, and the wheel is slowed to where the input is maxed out, when the wheel is released it will spin for some time. For example, turn off the motor power and call setSpeed. Then turn the power back on and watch it spin!

Better would be to have a legit speed controller (with capped integral or whatever other trick we want to use). Alternatively, instead of "blindly" adding to the setPoint each loop, check to see what the current effort is -- if it's maxed out, reduce the delta in the setPoint. This has the effect of capping the integral.

**Comment by madhephaestus** [comment]
The behavior you described happens even with I term at 0. 

It happens because it is the setpoint that is moving away continuously. If the wheel stalls, it needs to catch back up to the controllers setpoint. It will accurately follow a trajectory and "in the long run" average will match what it would be if it had moved at the desired speed.

A simple fix would be to have it increment against the position instead of the setpoint. It will never overshoot the velocity, but it will not react as strongly to perturbations.

**Comment by gcl8a** [comment]
Right. Proportional control for position is integral control for speed — my terminology was a little misleading.

But you can’t just add to the current position — you’d end up at a lower speed. Best would be to check if you’ve “fallen too far behind” the rolling set point and decrease the increment. The easiest way to do that is probably to just check the motor effort. If it’s at 1.0 (or -1.0), it needs to be reduced.

Well, best would probably be to do something more traditional than my Red Queen method, but here we are…

Greg

**Comment by madhephaestus** [comment]
ok, i found the issue.

```
Setpoint = nowEncoder;
```

On set speed the encoder current value was being set as the setpoint. That was causing it to always lag in speed if set speed was called too fast. 

this issue is fixed in 0.5.3

**Comment by madhephaestus** [comment]
i also fixed the velocity run-away as you suggested here. If the effort from the last loop is >0.99 then the setpoint is not incremented. Once the effort comes down below saturated, then the setpoint begins running away again to set up the velovcity mode.
